[build]
  base = "/"
  publish = ""
  command = ""
  clientID = "CLIENT_ID"
  clientSecret = "CLIENT_SECRET"
  userID = "USER_ID"
[dev]
  publish = ""
  clientID = "CLIENT_ID"
  clientSecret = "CLIENT_SECRET"
  userID = "USER_ID"